apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    name: TestCafe POC Testing
    tags:
      - e2e
      - release team
      - other tag
    build: $BUILD_ID

suites:
  - name: "sauce_win10_chrome"
    browserName: "chrome"
    platformName: "Windows 10"
    src:
      - "**/shared/pdp.js" # test files glob
    screenshots:
      takeOnFails: true
      fullPage: true
    env:
      hello: world
    skipJsErrors: true

  - name: "sauce_win10_firefox"
    browserName: "firefox"
    platformName: "Windows 10"
    src:
      - "**/shared/pdp.js" # test files glob
    screenshots:
      takeOnFails: true
      fullPage: true
    env:
      hello: world
    skipJsErrors: true

  - name: "sauce_win10_edge"
    browserName: "microsoftedge"
    platformName: "Windows 10"
    src:
      - "**/shared/pdp.js" # test files glob
    screenshots:
      takeOnFails: true
      fullPage: true
    env:
      hello: world
    skipJsErrors: true

  - name: "sauce_win10_ie11"
    browserName: "internetexplorer"
    platformName: "Windows 10"
    src:
      - "**/shared/pdp.js" # test files glob
    screenshots:
      takeOnFails: true
      fullPage: true
    env:
      hello: world
    skipJsErrors: true

  - name: "sauce_os11_safari"
    browserName: "safari"
    src:
      - "**/shared/pdp.js" # test files glob
    screenshots:
      takeOnFails: true
      fullPage: true
    platformName: "mac 11.00"
    env:
      hello: world
    skipJsErrors: true

  - name: "sauce_Google_API_Emulator"
    mode: sauce
    browserName: "Chrome"
    skipJsErrors: true
    src:
      - "**/shared/pdp.js" # test files glob
    devices:
      - name: Samsung Galaxy S9 HD GoogleAPI Emulator
        platformName: Android
        platformVersions:
          - "9.0"

  - name: "sauce_iPhone_12"
    mode: sauce
    browserName: "safari"
    skipJsErrors: true
    src:
      - "**/shared/pdp.js" # test files glob
    devices:
      - name: iPhone 12 Simulator
        platformName: iOS
        platformVersions:
          - "14.3"

  - name: "sauce_iPad_mini"
    mode: sauce
    browserName: "safari"
    skipJsErrors: true
    src:
      - "**/shared/pdp.js" # test files glob
    devices:
      - name: iPad mini (5th generation) Simulator
        platformName: iOS
        platformVersions:
          - "14.3"

docker:
  fileTransfer: mount # Defaults to `mount`. Choose between mount|copy.
  image: saucelabs/stt-testcafe-node:v0.4.0

rootDir: ./

testcafe:
  version: 1.11.0
