apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    name: RENT NEXT-JS Testing (testcafe 1.11.0)
    tags:
      - e2e
      - release team
      - other tag
    build: $BUILD_ID

suites:
  - name: "sauce_os11_safari"
    browserName: "safari"
    src:
      - "**/shared/pdp.js" # test files glob
    screenshots:
      takeOnFails: true
      fullPage: false
    platformName: "mac 11.00"

docker:
  fileTransfer: mount # Defaults to `mount`. Choose between mount|copy.
  image: saucelabs/stt-testcafe-node:v0.4.0

rootDir: ./

testcafe:
  version: 1.11.0