apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
  concurrency: 1
  metadata:
    name: Testing Testcafe Support
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA
suites:
  - name: "saucy test"
    browserName: "chrome"
    src:
      - "*/*.js"
    screenshots:
      takeOnFails: true
      fullPage: true
    platformName: "windows 10"
    env:
      hello: world
    speed: 1
    screenResolution: "1920x1080"
docker:
  fileTransfer: mount
testcafe:
  projectPath: tests/e2e/testcafe
  version: 1.11.0